Phone book file
JoeJack404/Study pull request #2
Opened 2022-04-10 20:43 UTC by JoeJack404

2022-04-10 21:28 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/PhoneBook.cs
> +            string path = @"D:\Study\PhoneBook\Phonebook.txt";
Лучше указать относительный путь

2022-04-10 21:33 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/PhoneBook.cs
> +                Console.WriteLine("Телефонная книга пуста");
Оператор if-а оборачиваем в фигурные скобки, даже если он состоит из 1-ой строчки

2022-05-02 10:52 UTC, IvanZheleznyakov commented
Напоминаю про названия коммитов - лучше их делать более осмысленными, чтобы самому в общих чертах понимать, какие были внесены изменения.

2022-05-02 10:53 UTC, IvanZheleznyakov commented
![image](https://user-images.githubusercontent.com/10994784/166223258-5371d0a4-67ef-4842-96e4-b3bf19516a60.png)
Не уверен, что эти файлы нужны здесь.

2022-05-02 10:55 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/PhoneBook.cs
> +            ++Size;
Size - это по сути размер списка phoneBookRecords? List сам знает свой размер. Можно сделать Size вычисляемым свойством.

2022-05-02 10:56 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/PhoneBook.cs
> +                Console.WriteLine("Телефонная книга пуста");
Оборачиваем в фигурные скобки, даже если тело оператора из одной строчки.

2022-05-02 10:57 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/PhoneBook.cs
> +            string path = @"D:\Study\PhoneBook\Phonebook.txt";
Напоминаю: нужно использовать относительные пути.

2022-05-02 10:58 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/PhoneBook.cs
> +                    phoneBookFile.Write(breakLine);
Обсуждали: строим сразу целую строчку, потом записываем ее в файл.

2022-05-02 10:59 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/PhoneBook.cs
> +            string path = @"D:\Study\PhoneBook\Phonebook.txt";
Относительные пути.

2022-05-02 10:59 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/Program.cs
> +                        phoneBook.PrintRecords();
Тело оператора case в фигурных скобках договорились писать.

2022-05-02 11:01 UTC, IvanZheleznyakov requested changes
Правим замечания - и в продакшн!

2022-05-04 16:41 UTC, IvanZheleznyakov commented
![image](https://user-images.githubusercontent.com/10994784/166729617-a4c2476c-a304-414e-a4b6-6bdcc13f7009.png)
Этот файл всё-таки нужен?

2022-05-04 16:46 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/PhoneBook.cs
> +                size = phoneBookRecords.Count;
И что, оно прям работает?

2022-05-04 16:46 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/PhoneBook.cs
> +            string path = "phoneBookFile.txt";
Тогда уж не path, а какой-нибудь fileName.

2022-05-04 16:46 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/PhoneBook.cs
> +            string path = "phoneBookFile.txt";
Тогда уж не path, а какой-нибудь fileName.

2022-05-04 16:47 UTC, IvanZheleznyakov requested changes
Есть замечания.

2022-05-04 16:48 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/Program.cs
> +                        phoneBook.PrintRecords();
Не исправлено.

2022-05-04 16:49 UTC, IvanZheleznyakov commented on PhoneBook/PhoneBook/PhoneBook.cs
> +                    phoneBookFile.Write(breakLine);
Не исправлено.

2022-05-04 16:59 UTC, JoeJack404 commented
> ![image](https://user-images.githubusercontent.com/10994784/166729617-a4c2476c-a304-414e-a4b6-6bdcc13f7009.png) Этот файл всё-таки нужен?

Удалял все файлы лишние, видимо они создаются заново

2022-05-04 17:14 UTC, IvanZheleznyakov commented
Хитро.
public Size { get { return phoneBookRecords.Count; } }

2022-05-04 17:16 UTC, IvanZheleznyakov commented
> 

Ок. Здесь давай оставим, а на будущее можно погуглить.

2022-05-04 17:17 UTC, IvanZheleznyakov commented
> > ![image](https://user-images.githubusercontent.com/10994784/166729617-a4c2476c-a304-414e-a4b6-6bdcc13f7009.png) Этот файл всё-таки нужен?
> 
> Удалял все файлы лишние, видимо они создаются заново

Ок. Здесь можешь оставить, а на будущее погугли, что ли.

2022-05-04 17:23 UTC, merged